name: Dummy Status Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy check
        run: echo "Status check passed!"
